# fly.toml app configuration file generated for apiclasher on 2024-12-07T23:25:29-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'apiclasher'
primary_region = 'gig'

[build]
  dockerfile = 'Dockerfile'

[env]
  FLASK_ENV = 'production'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true

  [http_service.concurrency]
    hard_limit = 50
    soft_limit = 25

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
