# fly.toml app configuration file generated for meu-projeto-flask-divine-glitter-7453 on 2024-12-07T22:36:05-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'meu-projeto-flask-divine-glitter-7453'
primary_region = 'gig'

[build]
  dockerfile = 'Dockerfile'

[env]
  FLASK_ENV = 'production'
  PORT = '8080'

[[mounts]]
  source = 'meu_volume'
  destination = '/app/data'

[http_service]
  internal_port = 8080
  force_https = true

  [http_service.concurrency]
    hard_limit = 50
    soft_limit = 25

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
